package cz.catparadiseprojekt.catparadisehotel.model;

public enum RoomType {
    PROKOCKUSTANDART,
    PROKOCKUDELUXE,
    PROKOCKUSUITE,
    PROKOCKUAMAJITELESTANDART,
    PROKOCKUAMAJITELEDELUX,
    PROKOCKUAMAJITELESUITE
}
